/**
 * Created by xiaoconglau on 07/09/2017.
 */
export const SDKConfig = {
  MODE: {
    PUBLISH: 0,
    DEVELOP: 1,
  },
  CONNECT_MODE: {
    VIDEO_PATH: 0,
    DIRECTLY: 1
  },
  LOCALSTORAGE_SESSION_DATA_KEY: "SDK_LOCALSTORAGE_SESSION_DATA_KEY",
  LOCALSTORAGE_ROUND_ID_KEY:"SDK_LOCALSTORAGE_ROUND_ID_KEY",
  VERSION: "1.0",
  BROADCAST_TIME_INTERVAL: 4 * 1000,
  GLOBE_HOST_MESSAGE_CALLBACK_KEY:"SDK_GLOBE_HOST_MESSAGE_CALLBACK_KEY",
  GLOBE_WATCHER_MESSAGE_CALLBACK_KEY:"SDK_GLOBE_WATCHER_MESSAGE_CALLBACK_KEY",
  GLOBE_MODE_KEY:"SDK_GLOBE_MODE_KEY",
  GLOBE_DEBUG_LOG_TO_DI_KEY:"SDK_GLOBE_DEBUG_LOG_TO_DI_KEY",
  DI:{
    REQUEST_TYPE:0,
    RESPONSE_TYPE:1
  }
};